// Generated from packages/native/include/opentui.h and scripts/native-abi-pointers.ts.
// Run `bun run generate:abi` in packages/core. Do not edit.
// Inspect audit input: bun scripts/native-abi.ts --audit
// ABI audit SHA-256: 1722fc8626061d8a02a1782e68fa798b20dc3b78898b69c8c745212ebf36c371

export const nativeSymbols = {
  ot_scene_set_hooks: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_frame_step_with_geometry: {
    args: ["ptr", "buffer", "ptr", "buffer", "u32", "u32", "buffer", "buffer"],
    returns: "i32",
  },
  ot_scene_frame_cancel: { args: ["ptr", "buffer", "u64"], returns: "i32" },
  ot_scene_create_node: { args: ["ptr", "buffer", "u32", "u32", "buffer"], returns: "i32" },
  ot_scene_destroy_node: { args: ["ptr", "buffer"], returns: "i32" },
  ot_scene_move_node: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_scene_set_measure: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_scene_has_measure: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_mark_dirty: { args: ["ptr", "buffer"], returns: "i32" },
  ot_scene_set_style: { args: ["ptr", "buffer", "u32", "u32", "u32", "u32", "f32", "u32"], returns: "i32" },
  ot_scene_get_style: { args: ["ptr", "buffer", "u32", "u32", "u32", "buffer"], returns: "i32" },
  ot_scene_set_paint: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_flush: { args: ["ptr", "ptr", "u32", "ptr", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_scene_set_surface: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_scene_set_box_details: { args: ["ptr", "buffer", "buffer", "ptr", "u32", "ptr", "u32"], returns: "i32" },
  ot_scene_set_box_border_style: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_scene_set_viewport: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_scene_set_focus: { args: ["ptr", "buffer", "u32"], returns: "i32" },
  ot_scene_set_slider: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_set_arrow: { args: ["ptr", "buffer", "buffer", "ptr", "u32"], returns: "i32" },
  ot_scene_get_slider_thumb: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_set_text: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_scene_set_styled_text: { args: ["ptr", "buffer", "ptr", "u32", "ptr", "u32"], returns: "i32" },
  ot_scene_set_styled_text_with_links: {
    args: ["ptr", "buffer", "ptr", "u32", "ptr", "u32", "ptr", "u32"],
    returns: "i32",
  },
  ot_scene_set_text_options: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_set_text_selection: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_scene_get_text_selection: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_get_selected_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_scene_get_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_scene_get_text_info: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_get_text_lines: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_scene_get_layout: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_scene_paint: { args: ["ptr", "buffer", "buffer", "u32", "u32"], returns: "i32" },
  ot_scene_hit_test: { args: ["ptr", "buffer", "i32", "i32", "buffer"], returns: "i32" },
  ot_scene_get_stats: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_get_cursor_state: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_scene_frame_copy_buffer: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_scene_measure_layout: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_render_split: {
    args: ["ptr", "buffer", "ptr", "ptr", "u32", "u32", "u32", "buffer", "buffer"],
    returns: "i32",
  },
  ot_session_split_control: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_session_set_screen: { args: ["ptr", "buffer", "u32", "u32", "u32", "buffer", "u32"], returns: "i32" },
  ot_session_sync_detached: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_unicode_create: { args: ["ptr", "ptr", "u32", "u32", "buffer"], returns: "i32" },
  ot_unicode_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_unicode_get: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_buffer_draw_unicode: {
    args: ["ptr", "buffer", "ptr", "buffer", "u32", "i32", "i32", "buffer", "buffer", "u32"],
    returns: "i32",
  },
  ot_embedded_terminal_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_embedded_terminal_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_embedded_terminal_write: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_embedded_terminal_resize: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_embedded_terminal_command: { args: ["ptr", "buffer", "u32", "i32"], returns: "i32" },
  ot_embedded_terminal_set_selection: { args: ["ptr", "buffer", "u32", "u32", "u32", "u32"], returns: "i32" },
  ot_embedded_terminal_get_selected_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_embedded_terminal_compose: { args: ["ptr", "buffer", "buffer", "ptr", "i32", "i32"], returns: "i32" },
  ot_embedded_terminal_cursor_get: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_embedded_terminal_encode_key: {
    args: ["ptr", "buffer", "buffer", "ptr", "u32", "ptr", "u32", "ptr", "u32", "buffer"],
    returns: "i32",
  },
  ot_embedded_terminal_encode_mouse: { args: ["ptr", "buffer", "buffer", "buffer", "u32", "buffer"], returns: "i32" },
  ot_embedded_terminal_encode_paste: { args: ["ptr", "buffer", "ptr", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_embedded_terminal_encode_focus: { args: ["ptr", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_embedded_terminal_drain_responses: { args: ["ptr", "buffer", "buffer", "u32", "buffer"], returns: "i32" },
  ot_edit_buffer_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_edit_buffer_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_editor_view_create: { args: ["ptr", "buffer", "u32", "u32", "buffer"], returns: "i32" },
  ot_editor_view_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_syntax_style_create: { args: ["ptr", "buffer"], returns: "i32" },
  ot_syntax_style_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_edit_buffer_set_syntax_style: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_edit_buffer_set_text: { args: ["ptr", "buffer", "ptr", "u32", "u32"], returns: "i32" },
  ot_edit_buffer_insert_text: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_edit_buffer_delete_range: { args: ["ptr", "buffer", "u32", "u32", "u32", "u32"], returns: "i32" },
  ot_edit_buffer_set_cursor: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_edit_buffer_get_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_edit_buffer_get_info: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_edit_buffer_command: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_edit_buffer_history: { args: ["ptr", "buffer", "u32", "buffer", "u32", "buffer"], returns: "i32" },
  ot_edit_buffer_get_position: { args: ["ptr", "buffer", "u32", "u32", "u32", "buffer"], returns: "i32" },
  ot_edit_buffer_get_range: {
    args: ["ptr", "buffer", "u32", "u32", "u32", "u32", "u32", "ptr", "u32", "buffer"],
    returns: "i32",
  },
  ot_edit_buffer_set_defaults: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_syntax_style_register: { args: ["ptr", "buffer", "ptr", "u32", "buffer", "buffer"], returns: "i32" },
  ot_syntax_style_resolve: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_syntax_style_get_count: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_edit_buffer_highlight: { args: ["ptr", "buffer", "u32", "u32", "ptr"], returns: "i32" },
  ot_edit_buffer_get_highlights: { args: ["ptr", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_editor_view_set_viewport: { args: ["ptr", "buffer", "buffer", "u32", "u32"], returns: "i32" },
  ot_editor_view_get_viewport: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_editor_view_set_scroll_margin: { args: ["ptr", "buffer", "f32"], returns: "i32" },
  ot_editor_view_command: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_editor_view_replace_selection: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_editor_view_set_tab_color: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_editor_view_select: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_editor_view_get_info: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_editor_view_get_selection: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_editor_view_get_selected_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_editor_view_get_position: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_editor_view_get_lines: { args: ["ptr", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_editor_view_measure: { args: ["ptr", "buffer", "u32", "u32", "buffer"], returns: "i32" },
  ot_editor_view_set_placeholder: { args: ["ptr", "buffer", "ptr", "u32", "ptr", "u32"], returns: "i32" },
  ot_context_set_edit_event_callback: { args: ["ptr", "ptr"], returns: "i32" },
  ot_scene_set_editor_view: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_scene_set_editor_options: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_image_import_compat: { args: ["ptr", "u32", "buffer"], returns: "i32" },
  ot_image_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_scene_set_image: { args: ["ptr", "buffer", "ptr", "u32", "u32", "ptr"], returns: "i32" },
  ot_buffer_draw_image: { args: ["ptr", "buffer", "ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_session_set_image_resolution: { args: ["ptr", "buffer", "u32", "u32", "u32", "u32"], returns: "i32" },
  ot_text_buffer_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_text_buffer_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_text_buffer_view_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_text_buffer_view_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_text_buffer_set_text: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_text_buffer_append: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_text_buffer_clear: { args: ["ptr", "buffer", "u32"], returns: "i32" },
  ot_text_buffer_set_styled_text: { args: ["ptr", "buffer", "ptr", "u32", "ptr", "u32", "ptr", "u32"], returns: "i32" },
  ot_text_buffer_replace_styled_batch: {
    args: ["ptr", "buffer", "u32", "buffer", "u32", "buffer", "u32", "buffer", "u32", "buffer"],
    returns: "i32",
  },
  ot_text_buffer_set_syntax_style: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_text_buffer_get_info: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_text_buffer_get_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_get_range: { args: ["ptr", "buffer", "u32", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_set_defaults: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_set_tab_width: { args: ["ptr", "buffer", "u32"], returns: "i32" },
  ot_text_buffer_highlight: { args: ["ptr", "buffer", "u32", "u32", "ptr"], returns: "i32" },
  ot_text_buffer_get_highlights: { args: ["ptr", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_view_set_viewport: { args: ["ptr", "buffer", "buffer", "u32"], returns: "i32" },
  ot_text_buffer_view_command: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_text_buffer_view_set_tab_color: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_text_buffer_view_select: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_text_buffer_view_get_info: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_text_buffer_view_get_selected_text: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_view_get_lines: { args: ["ptr", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_text_buffer_view_measure: { args: ["ptr", "buffer", "u32", "u32", "buffer"], returns: "i32" },
  ot_scene_set_text_view: { args: ["ptr", "buffer", "ptr"], returns: "i32" },
  ot_scene_set_text_view_paint: { args: ["ptr", "buffer", "u32"], returns: "i32" },
  ot_scene_select_text_view_paint: { args: ["ptr", "buffer", "buffer", "u32"], returns: "i32" },
  ot_buffer_draw_text_view: { args: ["ptr", "buffer", "ptr", "buffer", "i32", "i32"], returns: "i32" },
  ot_buffer_draw_editor_view: { args: ["ptr", "buffer", "ptr", "buffer", "i32", "i32"], returns: "i32" },
  ot_buffer_draw_scene_text: { args: ["ptr", "buffer", "ptr", "buffer", "i32", "i32"], returns: "i32" },
  ot_scene_frame_acquire_buffer_lease: { args: ["ptr", "buffer", "buffer", "u32", "buffer"], returns: "i32" },
  ot_scene_frame_commit: { args: ["ptr", "buffer", "buffer", "u32", "buffer"], returns: "i32" },
  ot_context_abi_version: { args: [], returns: "u32" },
  ot_context_create: { args: ["buffer", "buffer"], returns: "i32" },
  ot_context_destroy: { args: ["ptr"], returns: "i32" },
  ot_context_get_last_error: { args: ["ptr", "buffer"], returns: "i32" },
  ot_context_drain_diagnostics: { args: ["ptr", "ptr", "u32", "buffer"], returns: "i32" },
  ot_buffer_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_buffer_destroy: { args: ["ptr", "buffer"], returns: "i32" },
  ot_buffer_resize: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_buffer_clear: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_buffer_fill_rect: { args: ["ptr", "buffer", "u32", "u32", "u32", "u32", "buffer"], returns: "i32" },
  ot_buffer_draw_text: { args: ["ptr", "buffer", "buffer", "ptr", "u32"], returns: "i32" },
  ot_buffer_draw: { args: ["ptr", "buffer", "ptr", "buffer", "ptr", "buffer", "u32", "buffer", "u32"], returns: "i32" },
  ot_buffer_stack: {
    args: ["ptr", "buffer", "ptr", "u32", "i32", "i32", "u32", "u32", "f32", "buffer"],
    returns: "i32",
  },
  ot_buffer_draw_grid: { args: ["ptr", "buffer", "ptr", "buffer", "buffer", "u32", "buffer", "u32"], returns: "i32" },
  ot_buffer_draw_packed: { args: ["ptr", "buffer", "ptr", "ptr", "u32", "u32", "u32", "u32", "u32"], returns: "i32" },
  ot_buffer_draw_supersample: {
    args: ["ptr", "buffer", "ptr", "ptr", "u32", "u32", "u32", "u32", "u32"],
    returns: "i32",
  },
  ot_buffer_draw_grayscale: {
    args: ["ptr", "buffer", "ptr", "buffer", "u32", "i32", "i32", "u32", "u32", "ptr", "ptr", "u32"],
    returns: "i32",
  },
  ot_buffer_color_matrix: {
    args: ["ptr", "buffer", "ptr", "buffer", "u32", "ptr", "u32", "f32", "u32"],
    returns: "i32",
  },
  ot_buffer_acquire_lease: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_create: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_attach_renderer: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_attach_renderer_with_env: { args: ["ptr", "buffer", "buffer", "buffer"], returns: "i32" },
  ot_session_render: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_session_resize_renderer: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_session_draw_buffer: { args: ["ptr", "buffer", "buffer", "i32", "i32"], returns: "i32" },
  ot_scene_frame_draw_buffer: { args: ["ptr", "buffer", "buffer", "buffer", "i32", "i32"], returns: "i32" },
  ot_session_set_debug_overlay: { args: ["ptr", "buffer", "u32", "u32"], returns: "i32" },
  ot_session_update_stats: { args: ["ptr", "buffer", "f64", "u32", "f64"], returns: "i32" },
  ot_session_update_memory_stats: { args: ["ptr", "buffer", "u32", "u32", "u32"], returns: "i32" },
  ot_session_dump_hit_grid: { args: ["ptr", "buffer"], returns: "i32" },
  ot_session_get_renderer_state: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_acquire_buffer_lease: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_buffer_lease_validate: { args: ["ptr", "buffer"], returns: "i32" },
  ot_buffer_lease_release: { args: ["ptr", "buffer"], returns: "i32" },
  ot_buffer_lease_get_real_char_size: { args: ["ptr", "buffer", "u32", "buffer"], returns: "i32" },
  ot_buffer_lease_write_resolved_chars: {
    args: ["ptr", "buffer", "ptr", "u32", "u32", "ptr", "u32", "buffer"],
    returns: "i32",
  },
  ot_session_setup_terminal: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_suspend: { args: ["ptr", "buffer"], returns: "i32" },
  ot_session_resume: { args: ["ptr", "buffer"], returns: "i32" },
  ot_session_get_terminal_state: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_control: { args: ["ptr", "buffer", "buffer", "ptr", "u32"], returns: "i32" },
  ot_session_get_capabilities: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_clipboard: { args: ["ptr", "buffer", "u32", "buffer", "u32", "buffer"], returns: "i32" },
  ot_session_set_palette_state: { args: ["ptr", "buffer", "buffer", "u32", "buffer", "buffer", "u32"], returns: "i32" },
  ot_session_notification: { args: ["ptr", "buffer", "buffer", "u32", "ptr", "u32", "buffer"], returns: "i32" },
  ot_session_pump: { args: ["ptr", "buffer", "u64", "u32", "buffer"], returns: "i32" },
  ot_session_get_write_limit: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_write: { args: ["ptr", "buffer", "ptr", "u32"], returns: "i32" },
  ot_session_read_output: { args: ["ptr", "buffer", "ptr", "u32", "buffer"], returns: "i32" },
  ot_session_complete_output: { args: ["ptr", "buffer", "buffer", "u32"], returns: "i32" },
  ot_session_close: { args: ["ptr", "buffer"], returns: "i32" },
  ot_session_pump_exit: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_cancel: { args: ["ptr", "buffer"], returns: "i32" },
  ot_session_get_state: { args: ["ptr", "buffer", "buffer"], returns: "i32" },
  ot_session_destroy: { args: ["ptr", "buffer"], returns: "i32" },
} as const

export const nativeCallbacks = {
  ot_scene_measure_callback: { args: ["u64", "u32", "u32", "f32", "u32", "f32", "u32", "ptr"], returns: "void" },
  ot_edit_event_callback: { args: ["u64", "u32", "u32", "u32"], returns: "void" },
} as const

export const nativeLayouts = {
  ot_handle: {
    size: 16,
    alignment: 8,
    fields: {
      context_id: { offset: 0, size: 8, alignment: 8, type: "u64" },
      slot: { offset: 8, size: 4, alignment: 4, type: "u32" },
      generation: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_slider_options: {
    size: 64,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      orientation: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      min: { offset: 16, size: 8, alignment: 8, type: "f64" },
      max: { offset: 24, size: 8, alignment: 8, type: "f64" },
      value: { offset: 32, size: 8, alignment: 8, type: "f64" },
      viewport_size: { offset: 40, size: 8, alignment: 8, type: "f64" },
      foreground: { offset: 48, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 56, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_scene_slider_thumb: {
    size: 24,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      size: { offset: 8, size: 8, alignment: 8, type: "f64" },
      start: { offset: 16, size: 8, alignment: 8, type: "f64" },
    },
  },
  ot_scene_arrow_options: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      direction: { offset: 8, size: 4, alignment: 4, type: "u32" },
      attributes: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_scene_text_options: {
    size: 72,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 8, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      attributes: { offset: 24, size: 4, alignment: 4, type: "u32" },
      wrap_mode: { offset: 28, size: 4, alignment: 4, type: "u32" },
      truncate: { offset: 32, size: 4, alignment: 4, type: "u32" },
      first_line_offset: { offset: 36, size: 4, alignment: 4, type: "u32" },
      scroll_x: { offset: 40, size: 8, alignment: 8, type: "f64" },
      scroll_y: { offset: 48, size: 8, alignment: 8, type: "f64" },
      tab_indicator: { offset: 56, size: 4, alignment: 4, type: "u32" },
      tab_color_set: { offset: 60, size: 4, alignment: 4, type: "u32" },
      tab_color: { offset: 64, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_scene_text_selection_options: {
    size: 56,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      operation: { offset: 8, size: 4, alignment: 4, type: "u32" },
      behavior: { offset: 12, size: 4, alignment: 4, type: "u32" },
      anchor_x: { offset: 16, size: 4, alignment: 4, type: "i32" },
      anchor_y: { offset: 20, size: 4, alignment: 4, type: "i32" },
      focus_x: { offset: 24, size: 4, alignment: 4, type: "i32" },
      focus_y: { offset: 28, size: 4, alignment: 4, type: "i32" },
      flags: { offset: 32, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 36, size: 4, alignment: 4, type: "u32" },
      background: { offset: 40, size: 8, alignment: 2, type: "[4]u16" },
      foreground: { offset: 48, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_scene_text_chunk: {
    size: 40,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      attributes: { offset: 32, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 36, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_linked_text_chunk: {
    size: 48,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      attributes: { offset: 32, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 36, size: 4, alignment: 4, type: "u32" },
      link_offset: { offset: 40, size: 4, alignment: 4, type: "u32" },
      link_byte_count: { offset: 44, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_text_info: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      text_length: { offset: 12, size: 4, alignment: 4, type: "u32" },
      line_count: { offset: 16, size: 4, alignment: 4, type: "u32" },
      virtual_line_count: { offset: 20, size: 4, alignment: 4, type: "u32" },
      width_cols_max: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_text_line: {
    size: 16,
    alignment: 4,
    fields: {
      start_cols: { offset: 0, size: 4, alignment: 4, type: "u32" },
      width_cols: { offset: 4, size: 4, alignment: 4, type: "u32" },
      source_line: { offset: 8, size: 4, alignment: 4, type: "u32" },
      wrap_index: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_paint_options: {
    size: 80,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      z_index: { offset: 8, size: 4, alignment: 4, type: "i32" },
      opacity: { offset: 12, size: 4, alignment: 4, type: "f32" },
      translate_x: { offset: 16, size: 8, alignment: 8, type: "f64" },
      translate_y: { offset: 24, size: 8, alignment: 8, type: "f64" },
      border_sides: { offset: 32, size: 4, alignment: 4, type: "u32" },
      should_fill: { offset: 36, size: 4, alignment: 4, type: "u32" },
      background: { offset: 40, size: 8, alignment: 2, type: "[4]u16" },
      border_color: { offset: 48, size: 8, alignment: 2, type: "[4]u16" },
      border_style: { offset: 56, size: 4, alignment: 4, type: "u32" },
      focusable: { offset: 60, size: 4, alignment: 4, type: "u32" },
      focused_border_color: { offset: 64, size: 8, alignment: 2, type: "[4]u16" },
      reserved: { offset: 72, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_box_details: {
    size: 76,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      title_alignment: { offset: 8, size: 4, alignment: 4, type: "u32" },
      bottom_title_alignment: { offset: 12, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 4, alignment: 4, type: "u32" },
      title_color: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      border_characters: { offset: 32, size: 44, alignment: 4, type: "[11]u32" },
    },
  },
  ot_scene_style_value: {
    size: 16,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      unit: { offset: 8, size: 4, alignment: 4, type: "u32" },
      value: { offset: 12, size: 4, alignment: 4, type: "f32" },
    },
  },
  ot_scene_layout: {
    size: 48,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      left: { offset: 8, size: 4, alignment: 4, type: "f32" },
      top: { offset: 12, size: 4, alignment: 4, type: "f32" },
      right: { offset: 16, size: 4, alignment: 4, type: "f32" },
      bottom: { offset: 20, size: 4, alignment: 4, type: "f32" },
      width: { offset: 24, size: 4, alignment: 4, type: "f32" },
      height: { offset: 28, size: 4, alignment: 4, type: "f32" },
      screen_x: { offset: 32, size: 8, alignment: 8, type: "f64" },
      screen_y: { offset: 40, size: 8, alignment: 8, type: "f64" },
    },
  },
  ot_scene_stats: {
    size: 64,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      last_frame_time: { offset: 8, size: 8, alignment: 8, type: "f64" },
      average_frame_time: { offset: 16, size: 8, alignment: 8, type: "f64" },
      render_time: { offset: 24, size: 8, alignment: 8, type: "f64" },
      stdout_write_time: { offset: 32, size: 8, alignment: 8, type: "f64" },
      frame_count: { offset: 40, size: 8, alignment: 8, type: "u64" },
      cells_updated: { offset: 48, size: 4, alignment: 4, type: "u32" },
      average_cells_updated: { offset: 52, size: 4, alignment: 4, type: "u32" },
      render_time_valid: { offset: 56, size: 4, alignment: 4, type: "u32" },
      stdout_write_time_valid: { offset: 60, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_cursor_state: {
    size: 48,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      x: { offset: 8, size: 4, alignment: 4, type: "u32" },
      y: { offset: 12, size: 4, alignment: 4, type: "u32" },
      visible: { offset: 16, size: 4, alignment: 4, type: "u32" },
      style: { offset: 20, size: 4, alignment: 4, type: "u32" },
      blinking: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
      r: { offset: 32, size: 4, alignment: 4, type: "f32" },
      g: { offset: 36, size: 4, alignment: 4, type: "f32" },
      b: { offset: 40, size: 4, alignment: 4, type: "f32" },
      a: { offset: 44, size: 4, alignment: 4, type: "f32" },
    },
  },
  ot_scene_hooks: {
    size: 40,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      generation: { offset: 16, size: 8, alignment: 8, type: "u64" },
      initial_width: { offset: 24, size: 8, alignment: 8, type: "f64" },
      initial_height: { offset: 32, size: 8, alignment: 8, type: "f64" },
    },
  },
  ot_scene_frame_options: {
    size: 36,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      background: { offset: 8, size: 8, alignment: 2, type: "[4]u16" },
      use_mouse: { offset: 16, size: 4, alignment: 4, type: "u32" },
      excluded_hit_num: { offset: 20, size: 4, alignment: 4, type: "u32" },
      max_layout_rounds: { offset: 24, size: 4, alignment: 4, type: "u32" },
      max_host_requests: { offset: 28, size: 4, alignment: 4, type: "u32" },
      preserve_unwritten: { offset: 32, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_frame_request: {
    size: 112,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      session: { offset: 8, size: 16, alignment: 8, type: "ot_handle" },
      root: { offset: 24, size: 16, alignment: 8, type: "ot_handle" },
      node: { offset: 40, size: 16, alignment: 8, type: "ot_handle" },
      frame_id: { offset: 56, size: 8, alignment: 8, type: "u64" },
      request_id: { offset: 64, size: 8, alignment: 8, type: "u64" },
      layout_epoch: { offset: 72, size: 8, alignment: 8, type: "u64" },
      hook_generation: { offset: 80, size: 8, alignment: 8, type: "u64" },
      kind: { offset: 88, size: 4, alignment: 4, type: "u32" },
      num: { offset: 92, size: 4, alignment: 4, type: "u32" },
      width: { offset: 96, size: 4, alignment: 4, type: "u32" },
      height: { offset: 100, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 104, size: 8, alignment: 4, type: "[2]u32" },
    },
  },
  ot_scene_frame_geometry: {
    size: 112,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      paint: { offset: 16, size: 48, alignment: 8, type: "ot_scene_layout" },
      public_layout: { offset: 64, size: 48, alignment: 8, type: "ot_scene_layout" },
    },
  },
  ot_scene_style_update: {
    size: 40,
    alignment: 8,
    fields: {
      node: { offset: 0, size: 16, alignment: 8, type: "ot_handle" },
      group: { offset: 16, size: 4, alignment: 4, type: "u32" },
      kind: { offset: 20, size: 4, alignment: 4, type: "u32" },
      edge: { offset: 24, size: 4, alignment: 4, type: "u32" },
      unit: { offset: 28, size: 4, alignment: 4, type: "u32" },
      value: { offset: 32, size: 4, alignment: 4, type: "f32" },
      flags: { offset: 36, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_background_update: {
    size: 32,
    alignment: 8,
    fields: {
      node: { offset: 0, size: 16, alignment: 8, type: "ot_handle" },
      fields: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 4, alignment: 4, type: "u32" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_scene_paint_update: {
    size: 96,
    alignment: 8,
    fields: {
      node: { offset: 0, size: 16, alignment: 8, type: "ot_handle" },
      paint: { offset: 16, size: 80, alignment: 8, type: "ot_scene_paint_options" },
    },
  },
  ot_session_options: {
    size: 32,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      chunk_size: { offset: 8, size: 4, alignment: 4, type: "u32" },
      span_capacity: { offset: 12, size: 4, alignment: 4, type: "u32" },
      max_bytes: { offset: 16, size: 8, alignment: 8, type: "u64" },
      control_capacity: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_output_ticket: {
    size: 32,
    alignment: 8,
    fields: {
      session: { offset: 0, size: 16, alignment: 8, type: "ot_handle" },
      request_id: { offset: 16, size: 8, alignment: 8, type: "u64" },
      byte_count: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_session_renderer_options: {
    size: 24,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      width: { offset: 8, size: 4, alignment: 4, type: "u32" },
      height: { offset: 12, size: 4, alignment: 4, type: "u32" },
      remote: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_session_renderer_env_options: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      width: { offset: 8, size: 4, alignment: 4, type: "u32" },
      height: { offset: 12, size: 4, alignment: 4, type: "u32" },
      remote_mode: { offset: 16, size: 4, alignment: 4, type: "u32" },
      entry_count: { offset: 20, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_split_snapshot: {
    size: 24,
    alignment: 8,
    fields: {
      buffer: { offset: 0, size: 16, alignment: 8, type: "ot_handle" },
      row_columns: { offset: 16, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_split_control: {
    size: 36,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      command: { offset: 8, size: 4, alignment: 4, type: "u32" },
      arguments: { offset: 12, size: 24, alignment: 4, type: "[6]u32" },
    },
  },
  ot_session_renderer_state: {
    size: 32,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      width: { offset: 8, size: 4, alignment: 4, type: "u32" },
      height: { offset: 12, size: 4, alignment: 4, type: "u32" },
      frame_count: { offset: 16, size: 8, alignment: 8, type: "u64" },
      frame_pending: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_buffer_options: {
    size: 24,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      width: { offset: 8, size: 4, alignment: 4, type: "u32" },
      height: { offset: 12, size: 4, alignment: 4, type: "u32" },
      width_method: { offset: 16, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_unicode_char: {
    size: 8,
    alignment: 4,
    fields: {
      width: { offset: 0, size: 4, alignment: 4, type: "u32" },
      character: { offset: 4, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_embedded_terminal_options: {
    size: 24,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      cols: { offset: 8, size: 4, alignment: 4, type: "u32" },
      rows: { offset: 12, size: 4, alignment: 4, type: "u32" },
      max_scrollback: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_embedded_terminal_cursor: {
    size: 56,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      x: { offset: 8, size: 4, alignment: 4, type: "u32" },
      y: { offset: 12, size: 4, alignment: 4, type: "u32" },
      has_value: { offset: 16, size: 4, alignment: 4, type: "u32" },
      visible: { offset: 20, size: 4, alignment: 4, type: "u32" },
      blinking: { offset: 24, size: 4, alignment: 4, type: "u32" },
      wide_tail: { offset: 28, size: 4, alignment: 4, type: "u32" },
      style: { offset: 32, size: 4, alignment: 4, type: "u32" },
      color_has_value: { offset: 36, size: 4, alignment: 4, type: "u32" },
      color_r: { offset: 40, size: 4, alignment: 4, type: "u32" },
      color_g: { offset: 44, size: 4, alignment: 4, type: "u32" },
      color_b: { offset: 48, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 52, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_embedded_terminal_key: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      action: { offset: 8, size: 4, alignment: 4, type: "u32" },
      composing: { offset: 12, size: 4, alignment: 4, type: "u32" },
      mods: { offset: 16, size: 4, alignment: 4, type: "u32" },
      consumed_mods: { offset: 20, size: 4, alignment: 4, type: "u32" },
      unshifted_codepoint: { offset: 24, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_embedded_terminal_mouse: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      action: { offset: 8, size: 4, alignment: 4, type: "u32" },
      button: { offset: 12, size: 4, alignment: 4, type: "i32" },
      mods: { offset: 16, size: 4, alignment: 4, type: "u32" },
      any_button_pressed: { offset: 20, size: 4, alignment: 4, type: "u32" },
      x: { offset: 24, size: 4, alignment: 4, type: "f32" },
      y: { offset: 28, size: 4, alignment: 4, type: "f32" },
    },
  },
  ot_edit_buffer_options: {
    size: 16,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      width_method: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_edit_buffer_info: {
    size: 48,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      content_epoch: { offset: 8, size: 8, alignment: 8, type: "u64" },
      byte_count: { offset: 16, size: 4, alignment: 4, type: "u32" },
      line_count: { offset: 20, size: 4, alignment: 4, type: "u32" },
      cursor_row: { offset: 24, size: 4, alignment: 4, type: "u32" },
      cursor_col: { offset: 28, size: 4, alignment: 4, type: "u32" },
      cursor_offset: { offset: 32, size: 4, alignment: 4, type: "u32" },
      can_undo: { offset: 36, size: 4, alignment: 4, type: "u32" },
      can_redo: { offset: 40, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 44, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_scene_editor_options: {
    size: 40,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      show_cursor: { offset: 8, size: 4, alignment: 4, type: "u32" },
      style: { offset: 12, size: 4, alignment: 4, type: "u32" },
      blinking: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 4, alignment: 4, type: "u32" },
      color: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      mouse_pointer: { offset: 32, size: 4, alignment: 4, type: "u32" },
      reserved2: { offset: 36, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_edit_position: {
    size: 24,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      valid: { offset: 8, size: 4, alignment: 4, type: "u32" },
      row: { offset: 12, size: 4, alignment: 4, type: "u32" },
      col: { offset: 16, size: 4, alignment: 4, type: "u32" },
      offset: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_editor_style: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      attributes: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_edit_highlight: {
    size: 20,
    alignment: 4,
    fields: {
      start: { offset: 0, size: 4, alignment: 4, type: "u32" },
      end: { offset: 4, size: 4, alignment: 4, type: "u32" },
      style_id: { offset: 8, size: 4, alignment: 4, type: "u32" },
      priority: { offset: 12, size: 4, alignment: 4, type: "u32" },
      ref: { offset: 16, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_editor_viewport: {
    size: 24,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      x: { offset: 8, size: 4, alignment: 4, type: "u32" },
      y: { offset: 12, size: 4, alignment: 4, type: "u32" },
      width: { offset: 16, size: 4, alignment: 4, type: "u32" },
      height: { offset: 20, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_editor_selection: {
    size: 72,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      operation: { offset: 8, size: 4, alignment: 4, type: "u32" },
      behavior: { offset: 12, size: 4, alignment: 4, type: "u32" },
      start: { offset: 16, size: 4, alignment: 4, type: "u32" },
      end: { offset: 20, size: 4, alignment: 4, type: "u32" },
      anchor_x: { offset: 24, size: 4, alignment: 4, type: "i32" },
      anchor_y: { offset: 28, size: 4, alignment: 4, type: "i32" },
      focus_x: { offset: 32, size: 4, alignment: 4, type: "i32" },
      focus_y: { offset: 36, size: 4, alignment: 4, type: "i32" },
      update_cursor: { offset: 40, size: 4, alignment: 4, type: "u32" },
      follow_cursor: { offset: 44, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 48, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 52, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 56, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 64, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_editor_view_info: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      virtual_line_count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      total_virtual_line_count: { offset: 12, size: 4, alignment: 4, type: "u32" },
      selection_present: { offset: 16, size: 4, alignment: 4, type: "u32" },
      selection_start: { offset: 20, size: 4, alignment: 4, type: "u32" },
      selection_end: { offset: 24, size: 4, alignment: 4, type: "u32" },
      selection_occupancy: { offset: 28, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_editor_position: {
    size: 28,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      visual_row: { offset: 8, size: 4, alignment: 4, type: "u32" },
      visual_col: { offset: 12, size: 4, alignment: 4, type: "u32" },
      logical_row: { offset: 16, size: 4, alignment: 4, type: "u32" },
      logical_col: { offset: 20, size: 4, alignment: 4, type: "u32" },
      offset: { offset: 24, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_editor_measure: {
    size: 16,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      line_count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      width_cols_max: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_image_draw_options: {
    size: 64,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      protocol: { offset: 12, size: 4, alignment: 4, type: "u32" },
      x: { offset: 16, size: 4, alignment: 4, type: "i32" },
      y: { offset: 20, size: 4, alignment: 4, type: "i32" },
      width: { offset: 24, size: 4, alignment: 4, type: "u32" },
      height: { offset: 28, size: 4, alignment: 4, type: "u32" },
      pixel_width: { offset: 32, size: 4, alignment: 4, type: "u32" },
      pixel_height: { offset: 36, size: 4, alignment: 4, type: "u32" },
      source_x: { offset: 40, size: 4, alignment: 4, type: "u32" },
      source_y: { offset: 44, size: 4, alignment: 4, type: "u32" },
      source_width: { offset: 48, size: 4, alignment: 4, type: "u32" },
      source_height: { offset: 52, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 56, size: 8, alignment: 4, type: "[2]u32" },
    },
  },
  ot_text_buffer_info: {
    size: 40,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      content_epoch: { offset: 8, size: 8, alignment: 8, type: "u64" },
      byte_count: { offset: 16, size: 4, alignment: 4, type: "u32" },
      text_length: { offset: 20, size: 4, alignment: 4, type: "u32" },
      line_count: { offset: 24, size: 4, alignment: 4, type: "u32" },
      highlight_count: { offset: 28, size: 4, alignment: 4, type: "u32" },
      tab_width: { offset: 32, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 36, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_text_buffer_replacement: {
    size: 56,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      buffer: { offset: 8, size: 16, alignment: 8, type: "ot_handle" },
      view: { offset: 24, size: 16, alignment: 8, type: "ot_handle" },
      byte_offset: { offset: 40, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 44, size: 4, alignment: 4, type: "u32" },
      chunk_offset: { offset: 48, size: 4, alignment: 4, type: "u32" },
      chunk_count: { offset: 52, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_text_buffer_replacement_info: {
    size: 8,
    alignment: 4,
    fields: {
      text_length: { offset: 0, size: 4, alignment: 4, type: "u32" },
      byte_count: { offset: 4, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_buffer_text_options: {
    size: 40,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      x: { offset: 8, size: 4, alignment: 4, type: "u32" },
      y: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      attributes: { offset: 32, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 36, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_buffer_draw_options: {
    size: 136,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      operation: { offset: 8, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 12, size: 4, alignment: 4, type: "u32" },
      x: { offset: 16, size: 4, alignment: 4, type: "i32" },
      y: { offset: 20, size: 4, alignment: 4, type: "i32" },
      width: { offset: 24, size: 4, alignment: 4, type: "u32" },
      height: { offset: 28, size: 4, alignment: 4, type: "u32" },
      character: { offset: 32, size: 4, alignment: 4, type: "u32" },
      attributes: { offset: 36, size: 4, alignment: 4, type: "u32" },
      packed_options: { offset: 40, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 44, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 48, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 56, size: 8, alignment: 2, type: "[4]u16" },
      title_color: { offset: 64, size: 8, alignment: 2, type: "[4]u16" },
      border_chars: { offset: 72, size: 44, alignment: 4, type: "[11]u32" },
      source_x: { offset: 116, size: 4, alignment: 4, type: "u32" },
      source_y: { offset: 120, size: 4, alignment: 4, type: "u32" },
      source_width: { offset: 124, size: 4, alignment: 4, type: "u32" },
      source_height: { offset: 128, size: 4, alignment: 4, type: "u32" },
      reserved2: { offset: 132, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_buffer_grid_options: {
    size: 76,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      foreground: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
      background: { offset: 24, size: 8, alignment: 2, type: "[4]u16" },
      border_chars: { offset: 32, size: 44, alignment: 4, type: "[11]u32" },
    },
  },
  ot_buffer_lease_snapshot: {
    size: 80,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      lease: { offset: 8, size: 16, alignment: 8, type: "ot_handle" },
      width: { offset: 24, size: 4, alignment: 4, type: "u32" },
      height: { offset: 28, size: 4, alignment: 4, type: "u32" },
      generation: { offset: 32, size: 8, alignment: 8, type: "u64" },
      char_ptr: { offset: 40, size: 8, alignment: 8, type: "u64" },
      fg_ptr: { offset: 48, size: 8, alignment: 8, type: "u64" },
      bg_ptr: { offset: 56, size: 8, alignment: 8, type: "u64" },
      attributes_ptr: { offset: 64, size: 8, alignment: 8, type: "u64" },
      reserved: { offset: 72, size: 8, alignment: 8, type: "u64" },
    },
  },
  ot_session_terminal_options: {
    size: 16,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      kitty_keyboard_flags: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_session_control_options: {
    size: 20,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      kind: { offset: 8, size: 4, alignment: 4, type: "u32" },
      argument: { offset: 12, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 16, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_session_cursor_update: {
    size: 24,
    alignment: 4,
    fields: {
      fields: { offset: 0, size: 4, alignment: 4, type: "u32" },
      x: { offset: 4, size: 4, alignment: 4, type: "i32" },
      y: { offset: 8, size: 4, alignment: 4, type: "i32" },
      visible: { offset: 12, size: 1, alignment: 1, type: "u8" },
      style: { offset: 13, size: 1, alignment: 1, type: "u8" },
      blinking: { offset: 14, size: 1, alignment: 1, type: "u8" },
      mouse_pointer: { offset: 15, size: 1, alignment: 1, type: "u8" },
      color: { offset: 16, size: 8, alignment: 2, type: "[4]u16" },
    },
  },
  ot_session_capabilities: {
    size: 144,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      width_method: { offset: 12, size: 4, alignment: 4, type: "u32" },
      multiplexer: { offset: 16, size: 4, alignment: 4, type: "u32" },
      image_protocol: { offset: 20, size: 4, alignment: 4, type: "u32" },
      osc52_support: { offset: 24, size: 4, alignment: 4, type: "u32" },
      kitty_keyboard_flags: { offset: 28, size: 4, alignment: 4, type: "u32" },
      term_name_len: { offset: 32, size: 4, alignment: 4, type: "u32" },
      term_version_len: { offset: 36, size: 4, alignment: 4, type: "u32" },
      term_from_xtversion: { offset: 40, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 44, size: 4, alignment: 4, type: "u32" },
      term_name: { offset: 48, size: 64, alignment: 1, type: "[64]u8" },
      term_version: { offset: 112, size: 32, alignment: 1, type: "[32]u8" },
    },
  },
  ot_session_pump_result: {
    size: 24,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      status: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      deadline_ns: { offset: 16, size: 8, alignment: 8, type: "u64" },
    },
  },
  ot_context_options: {
    size: 32,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      object_capacity: { offset: 12, size: 4, alignment: 4, type: "u32" },
      render_cells_max: { offset: 16, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 20, size: 12, alignment: 4, type: "[3]u32" },
    },
  },
  ot_context_error: {
    size: 16,
    alignment: 4,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      status: { offset: 8, size: 4, alignment: 4, type: "i32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
    },
  },
  ot_diagnostic: {
    size: 4112,
    alignment: 4,
    fields: {
      level: { offset: 0, size: 4, alignment: 4, type: "u32" },
      message_len: { offset: 4, size: 4, alignment: 4, type: "u32" },
      flags: { offset: 8, size: 4, alignment: 4, type: "u32" },
      reserved: { offset: 12, size: 4, alignment: 4, type: "u32" },
      message: { offset: 16, size: 4096, alignment: 1, type: "[4096]u8" },
    },
  },
  ot_diagnostic_drain: {
    size: 24,
    alignment: 8,
    fields: {
      struct_size: { offset: 0, size: 4, alignment: 4, type: "u32" },
      abi_version: { offset: 4, size: 4, alignment: 4, type: "u32" },
      count: { offset: 8, size: 4, alignment: 4, type: "u32" },
      remaining: { offset: 12, size: 4, alignment: 4, type: "u32" },
      dropped: { offset: 16, size: 8, alignment: 8, type: "u64" },
    },
  },
} as const

export const nativeConstants = {
  OT_CONTEXT_ABI_VERSION: 1,
  OT_OK: 0,
  OT_INVALID_ARGUMENT: -1,
  OT_UNSUPPORTED_VERSION: -2,
  OT_OUT_OF_MEMORY: -3,
  OT_WRONG_THREAD: -4,
  OT_INTERNAL_ERROR: -5,
  OT_CONTEXT_BUSY: -6,
  OT_WRONG_CONTEXT: -7,
  OT_WRONG_KIND: -8,
  OT_STALE_HANDLE: -9,
  OT_WRONG_SESSION: -10,
  OT_OUTPUT_BACKPRESSURE: -11,
  OT_SESSION_CLOSED: -12,
  OT_OUTPUT_BUSY: -13,
  OT_STALE_OUTPUT: -14,
  OT_OUTPUT_FAILED: -15,
  OT_OBJECT_LIMIT: -16,
  OT_RENDERER_ATTACHED: -17,
  OT_RENDERER_NOT_ATTACHED: -18,
  OT_INVALID_PHASE: -19,
  OT_CONTROL_PACKET_LIMIT: -20,
  OT_LEASE_LIMIT: -21,
  OT_LEASE_BYTES_LIMIT: -22,
  OT_STALE_LEASE: -23,
  OT_UNSUPPORTED_RESOURCE: -24,
  OT_STALE_FRAME: -25,
  OT_LAYOUT_LIMIT: -26,
  OT_FRAME_BUSY: -27,
  OT_FRAME_REQUEST_LIMIT: -28,
  OT_SCENE_ROOT: 0,
  OT_SCENE_BOX: 1,
  OT_SCENE_TEXT: 2,
  OT_SCENE_SLIDER: 3,
  OT_SCENE_ARROW: 4,
  OT_SCENE_EDITOR: 5,
  OT_SCENE_CUSTOM: 6,
  OT_SCENE_TEXT_VIEW: 7,
  OT_SCENE_IMAGE: 8,
  OT_SCENE_WRAP_NONE: 0,
  OT_SCENE_WRAP_CHAR: 1,
  OT_SCENE_WRAP_WORD: 2,
  OT_SCENE_TEXT_SELECTION_RESET: 0,
  OT_SCENE_TEXT_SELECTION_SET: 1,
  OT_SCENE_TEXT_SELECTION_UPDATE: 2,
  OT_SCENE_TEXT_SELECTION_CELL: 0,
  OT_SCENE_TEXT_SELECTION_WORD: 1,
  OT_SCENE_TEXT_SELECTION_LINE: 2,
  OT_SCENE_TEXT_SELECTION_BACKGROUND: 1,
  OT_SCENE_TEXT_SELECTION_FOREGROUND: 2,
  OT_SCENE_TEXT_FOREGROUND: 1,
  OT_SCENE_TEXT_BACKGROUND: 2,
  OT_SCENE_TEXT_LINK: 4,
  OT_SCENE_MUTATIONS_MAX: 4096,
  OT_SCENE_HOOK_UPDATE: 1,
  OT_SCENE_HOOK_RESIZE: 2,
  OT_SCENE_HOOK_LAYOUT_CHANGED: 4,
  OT_SCENE_HOOK_RENDER_BEFORE: 8,
  OT_SCENE_HOOK_RENDER_AFTER: 16,
  OT_SCENE_HOOK_RENDER_SELF: 32,
  OT_SCENE_HOOK_IDLE_UPDATE: 64,
  OT_SCENE_HOOK_RESUME_NATIVE_TEXT: 128,
  OT_SCENE_FRAME_DONE: 0,
  OT_SCENE_FRAME_UPDATE: 1,
  OT_SCENE_FRAME_RESIZE: 2,
  OT_SCENE_FRAME_LAYOUT_CHANGED: 3,
  OT_SCENE_FRAME_RENDER_BEFORE: 4,
  OT_SCENE_FRAME_RENDER_AFTER: 5,
  OT_SCENE_FRAME_YIELD: 6,
  OT_SCENE_FRAME_RENDER_SELF: 7,
  OT_SCENE_GEOMETRY_PAINT: 1,
  OT_SCENE_GEOMETRY_PUBLIC: 2,
  OT_SCENE_UPDATE_SKIP: 0,
  OT_SCENE_UPDATE_APPLY: 1,
  OT_SESSION_OPEN: 0,
  OT_SESSION_CLOSING: 1,
  OT_SESSION_CLOSED_STATE: 2,
  OT_SESSION_FAILED: 3,
  OT_SESSION_CANCELLED_STATE: 4,
  OT_SESSION_REMOTE_AUTO: 0,
  OT_SESSION_REMOTE_LOCAL: 1,
  OT_SESSION_REMOTE_REMOTE: 2,
  OT_SESSION_ENV_ENTRIES_MAX: 256,
  OT_SESSION_ENV_BYTES_MAX: 65536,
  OT_RENDER_PRESENTED: 0,
  OT_RENDER_PENDING: 1,
  OT_RENDER_SKIPPED: 2,
  OT_RENDER_FAILED: 3,
  OT_SESSION_BUFFER_CURRENT: 0,
  OT_SESSION_BUFFER_NEXT: 1,
  OT_WIDTH_METHOD_WCWIDTH: 0,
  OT_WIDTH_METHOD_UNICODE: 1,
  OT_WIDTH_METHOD_NO_ZWJ: 2,
  OT_WIDTH_METHOD_UNICODE_WIDE: 3,
  OT_BUFFER_RESPECT_ALPHA: 1,
  OT_EMBEDDED_TERMINAL_INVALIDATE: 0,
  OT_EMBEDDED_TERMINAL_SCROLL: 1,
  OT_EMBEDDED_TERMINAL_CLEAR_SELECTION: 2,
  OT_EDIT_CURSOR_CHANGED: 1,
  OT_EDIT_CONTENT_CHANGED: 2,
  OT_EDIT_HISTORY_CURSOR_CHANGED: 4,
  OT_EDIT_DELETE_FORWARD: 0,
  OT_EDIT_BACKSPACE: 1,
  OT_EDIT_NEW_LINE: 2,
  OT_EDIT_DELETE_LINE: 3,
  OT_EDIT_MOVE_LEFT: 4,
  OT_EDIT_MOVE_RIGHT: 5,
  OT_EDIT_MOVE_UP: 6,
  OT_EDIT_MOVE_DOWN: 7,
  OT_EDIT_GOTO_LINE: 8,
  OT_EDIT_CURSOR_OFFSET: 9,
  OT_EDIT_CLEAR: 10,
  OT_EDIT_CLEAR_HISTORY: 11,
  OT_EDIT_DEBUG_ROPE: 12,
  OT_EDIT_POSITION_CURSOR: 0,
  OT_EDIT_POSITION_NEXT_WORD: 1,
  OT_EDIT_POSITION_PREV_WORD: 2,
  OT_EDIT_POSITION_EOL: 3,
  OT_EDIT_POSITION_OFFSET: 4,
  OT_EDIT_POSITION_COORDS: 5,
  OT_EDIT_POSITION_LINE_START: 6,
  OT_EDITOR_STYLE_FOREGROUND: 1,
  OT_EDITOR_STYLE_BACKGROUND: 2,
  OT_EDITOR_STYLE_ATTRIBUTES: 4,
  OT_EDIT_HIGHLIGHT_ADD_LINE: 0,
  OT_EDIT_HIGHLIGHT_ADD_RANGE: 1,
  OT_EDIT_HIGHLIGHT_REMOVE_REF: 2,
  OT_EDIT_HIGHLIGHT_CLEAR_LINE: 3,
  OT_EDIT_HIGHLIGHT_CLEAR_ALL: 4,
  OT_EDITOR_MOVE_UP: 0,
  OT_EDITOR_MOVE_DOWN: 1,
  OT_EDITOR_GOTO_LINE_END: 2,
  OT_EDITOR_DELETE_SELECTION: 3,
  OT_EDITOR_CURSOR_OFFSET: 4,
  OT_EDITOR_WRAP_MODE: 5,
  OT_EDITOR_TAB_INDICATOR: 6,
  OT_EDITOR_SELECT_SET: 0,
  OT_EDITOR_SELECT_UPDATE: 1,
  OT_EDITOR_SELECT_RESET: 2,
  OT_EDITOR_SELECT_LOCAL: 3,
  OT_EDITOR_SELECT_LOCAL_UPDATE: 4,
  OT_EDITOR_SELECT_LOCAL_RESET: 5,
  OT_EDITOR_SELECT_CELL: 6,
  OT_EDITOR_SELECT_OCCUPANCY: 7,
  OT_EDITOR_SELECT_INCLUSIVE: 8,
  OT_EDITOR_SELECT_COLORS: 9,
  OT_EDITOR_POSITION_CURSOR: 0,
  OT_EDITOR_POSITION_NEXT_WORD: 1,
  OT_EDITOR_POSITION_PREV_WORD: 2,
  OT_EDITOR_POSITION_EOL: 3,
  OT_EDITOR_POSITION_VISUAL_SOL: 4,
  OT_EDITOR_POSITION_VISUAL_EOL: 5,
  OT_IMAGE_FIT: 0,
  OT_IMAGE_COVER: 1,
  OT_IMAGE_FILL: 2,
  OT_IMAGE_PROTOCOL_AUTO: 0,
  OT_IMAGE_PROTOCOL_KITTY: 1,
  OT_IMAGE_PROTOCOL_SIXEL: 2,
  OT_IMAGE_PROTOCOL_BLOCKS: 3,
  OT_IMAGE_DRAW_SOURCE_WIDTH: 1,
  OT_IMAGE_DRAW_SOURCE_HEIGHT: 2,
  OT_TEXT_VIEW_WRAP_WIDTH: 0,
  OT_TEXT_VIEW_WRAP_MODE: 1,
  OT_TEXT_VIEW_FIRST_LINE_OFFSET: 2,
  OT_TEXT_VIEW_TAB_INDICATOR: 3,
  OT_TEXT_VIEW_TRUNCATE: 4,
  OT_TEXT_REPLACEMENT_COUNT_MAX: 256,
  OT_TEXT_REPLACEMENT_CHUNKS_MAX: 4096,
  OT_TEXT_REPLACEMENT_BYTES_MAX: 4194304,
  OT_TEXT_REPLACEMENT_URL_BYTES_MAX: 1048576,
  OT_BUFFER_TEXT_BYTES_MAX: 65536,
  OT_BUFFER_TEXT_HAS_BACKGROUND: 1,
  OT_BUFFER_DRAW_CLEAR: 0,
  OT_BUFFER_DRAW_FILL: 1,
  OT_BUFFER_DRAW_TEXT: 2,
  OT_BUFFER_DRAW_CELL: 3,
  OT_BUFFER_DRAW_CELL_BLEND: 4,
  OT_BUFFER_DRAW_CHAR: 5,
  OT_BUFFER_DRAW_BOX: 6,
  OT_BUFFER_DRAW_COMPOSE: 7,
  OT_BUFFER_DRAW_RESPECT_ALPHA: 8,
  OT_BUFFER_DRAW_HAS_BACKGROUND: 1,
  OT_BUFFER_DRAW_HAS_SOURCE_WIDTH: 2,
  OT_BUFFER_DRAW_HAS_SOURCE_HEIGHT: 4,
  OT_BUFFER_STACK_DEPTH_MAX: 256,
  OT_BUFFER_STACK_GET_OPACITY: 0,
  OT_BUFFER_STACK_PUSH_SCISSOR: 1,
  OT_BUFFER_STACK_POP_SCISSOR: 2,
  OT_BUFFER_STACK_CLEAR_SCISSORS: 3,
  OT_BUFFER_STACK_PUSH_OPACITY: 4,
  OT_BUFFER_STACK_POP_OPACITY: 5,
  OT_BUFFER_STACK_CLEAR_OPACITY: 6,
  OT_BUFFER_GRID_INNER: 1,
  OT_BUFFER_GRID_OUTER: 2,
  OT_SESSION_CONTROL_PACKET_BYTES: 4096,
  OT_TERMINAL_ALTERNATE_SCREEN: 1,
  OT_TERMINAL_MOUSE: 2,
  OT_TERMINAL_MOUSE_MOVEMENT: 4,
  OT_TERMINAL_CLEAR_ON_CLOSE: 8,
  OT_CONTROL_CAPABILITY_RESPONSE: 1,
  OT_CONTROL_TITLE: 2,
  OT_CONTROL_MOUSE: 3,
  OT_CONTROL_KITTY_KEYBOARD_FLAGS: 4,
  OT_CONTROL_RESTORE_MODES: 5,
  OT_CONTROL_QUERY_PIXEL_RESOLUTION: 6,
  OT_CONTROL_QUERY_THEME_COLORS: 7,
  OT_CONTROL_CURSOR: 8,
  OT_CONTROL_RESET_BACKGROUND: 9,
  OT_CONTROL_PALETTE_QUERY: 10,
  OT_CURSOR_POSITION: 1,
  OT_CURSOR_STYLE: 2,
  OT_CURSOR_BLINKING: 4,
  OT_CURSOR_COLOR: 8,
  OT_CURSOR_MOUSE_POINTER: 16,
  OT_CAP_KITTY_KEYBOARD: 1,
  OT_CAP_KITTY_GRAPHICS: 2,
  OT_CAP_RGB: 4,
  OT_CAP_ANSI256: 8,
  OT_CAP_SGR_PIXELS: 16,
  OT_CAP_COLOR_SCHEME_UPDATES: 32,
  OT_CAP_EXPLICIT_WIDTH: 64,
  OT_CAP_SCALED_TEXT: 128,
  OT_CAP_SIXEL: 256,
  OT_CAP_FOCUS_TRACKING: 512,
  OT_CAP_SYNC: 1024,
  OT_CAP_BRACKETED_PASTE: 2048,
  OT_CAP_HYPERLINKS: 4096,
  OT_CAP_OSC52: 8192,
  OT_CAP_NOTIFICATIONS: 16384,
  OT_CAP_EXPLICIT_CURSOR_POSITIONING: 32768,
  OT_CAP_REMOTE: 65536,
  OT_TERMINAL_UNINITIALIZED: 0,
  OT_TERMINAL_SETTING_UP: 1,
  OT_TERMINAL_ACTIVE: 2,
  OT_TERMINAL_SUSPENDING: 3,
  OT_TERMINAL_SUSPENDED: 4,
  OT_TERMINAL_RESUMING: 5,
  OT_TERMINAL_CLOSING: 6,
  OT_TERMINAL_RESTORED: 7,
  OT_TERMINAL_FAILED: 8,
  OT_TERMINAL_CANCELLED: 9,
  OT_PUMP_IDLE: 0,
  OT_PUMP_AGAIN: 1,
  OT_PUMP_OUTPUT_PENDING: 2,
  OT_PUMP_WAIT_UNTIL: 3,
  OT_PUMP_CLOSED: 4,
  OT_DIAGNOSTIC_MESSAGE_BYTES: 4096,
  OT_DIAGNOSTIC_TRUNCATED: 1,
} as const
