// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2026-04-05T15:48:16.057Z

import type { FiletypeParserOptions } from "./types"
import { fileURLToPath } from "url"

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        aliases: ["javascriptreact"],
        queries: {
          highlights: [fileURLToPath(new URL("./assets/javascript/highlights.scm", import.meta.url))],
        },
        wasm: fileURLToPath(new URL("./assets/javascript/tree-sitter-javascript.wasm", import.meta.url)),
      },
      {
        filetype: "typescript",
        aliases: ["typescriptreact"],
        queries: {
          highlights: [fileURLToPath(new URL("./assets/typescript/highlights.scm", import.meta.url))],
        },
        wasm: fileURLToPath(new URL("./assets/typescript/tree-sitter-typescript.wasm", import.meta.url)),
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [fileURLToPath(new URL("./assets/markdown/highlights.scm", import.meta.url))],
          injections: [fileURLToPath(new URL("./assets/markdown/injections.scm", import.meta.url))],
        },
        wasm: fileURLToPath(new URL("./assets/markdown/tree-sitter-markdown.wasm", import.meta.url)),
        injectionMapping: {
          "nodeTypes": {
                    "inline": "markdown_inline",
                    "pipe_table_cell": "markdown_inline"
          },
          "infoStringMap": {
                    "javascript": "javascript",
                    "js": "javascript",
                    "jsx": "javascriptreact",
                    "javascriptreact": "javascriptreact",
                    "typescript": "typescript",
                    "ts": "typescript",
                    "tsx": "typescriptreact",
                    "typescriptreact": "typescriptreact",
                    "markdown": "markdown",
                    "md": "markdown"
          }
},
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [fileURLToPath(new URL("./assets/markdown_inline/highlights.scm", import.meta.url))],
        },
        wasm: fileURLToPath(new URL("./assets/markdown_inline/tree-sitter-markdown_inline.wasm", import.meta.url)),
      },
      {
        filetype: "zig",
        queries: {
          highlights: [fileURLToPath(new URL("./assets/zig/highlights.scm", import.meta.url))],
        },
        wasm: fileURLToPath(new URL("./assets/zig/tree-sitter-zig.wasm", import.meta.url)),
      },
    ]
  }
  return _cachedParsers
}
