// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2026-03-20T21:07:24.696Z

import type { FiletypeParserOptions } from "./types.js"
import { fileURLToPath } from "url"

const javascript_highlights = new URL("./assets/javascript/highlights.scm", import.meta.url)
const javascript_language = new URL("./assets/javascript/tree-sitter-javascript.wasm", import.meta.url)
const typescript_highlights = new URL("./assets/typescript/highlights.scm", import.meta.url)
const typescript_language = new URL("./assets/typescript/tree-sitter-typescript.wasm", import.meta.url)
const markdown_highlights = new URL("./assets/markdown/highlights.scm", import.meta.url)
const markdown_language = new URL("./assets/markdown/tree-sitter-markdown.wasm", import.meta.url)
const markdown_injections = new URL("./assets/markdown/injections.scm", import.meta.url)
const markdown_inline_highlights = new URL("./assets/markdown_inline/highlights.scm", import.meta.url)
const markdown_inline_language = new URL("./assets/markdown_inline/tree-sitter-markdown_inline.wasm", import.meta.url)
const zig_highlights = new URL("./assets/zig/highlights.scm", import.meta.url)
const zig_language = new URL("./assets/zig/tree-sitter-zig.wasm", import.meta.url)

function toFilePath(url: URL): string {
  return fileURLToPath(url)
}

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        aliases: ["javascriptreact"],
        queries: {
          highlights: [toFilePath(javascript_highlights)],
        },
        wasm: toFilePath(javascript_language),
      },
      {
        filetype: "typescript",
        aliases: ["typescriptreact"],
        queries: {
          highlights: [toFilePath(typescript_highlights)],
        },
        wasm: toFilePath(typescript_language),
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [toFilePath(markdown_highlights)],
          injections: [toFilePath(markdown_injections)],
        },
        wasm: toFilePath(markdown_language),
        injectionMapping: {
          "nodeTypes": {
                    "inline": "markdown_inline",
                    "pipe_table_cell": "markdown_inline"
          },
          "infoStringMap": {
                    "javascript": "javascript",
                    "js": "javascript",
                    "jsx": "javascriptreact",
                    "javascriptreact": "javascriptreact",
                    "typescript": "typescript",
                    "ts": "typescript",
                    "tsx": "typescriptreact",
                    "typescriptreact": "typescriptreact",
                    "markdown": "markdown",
                    "md": "markdown"
          }
},
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [toFilePath(markdown_inline_highlights)],
        },
        wasm: toFilePath(markdown_inline_language),
      },
      {
        filetype: "zig",
        queries: {
          highlights: [toFilePath(zig_highlights)],
        },
        wasm: toFilePath(zig_language),
      },
    ]
  }
  return _cachedParsers
}
