// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file

import type { FiletypeParserOptions } from "./types.js"
import { resolveAssetPath } from "../../platform/assets.js"

let cachedParsers: Promise<FiletypeParserOptions[]> | undefined

export function getParsers(): Promise<FiletypeParserOptions[]> {
  if (!cachedParsers) {
    cachedParsers = loadParsers()
  }
  return cachedParsers
}

async function loadParsers(): Promise<FiletypeParserOptions[]> {
  const javascript_highlights = resolveAssetPath(
    "@opentui/core/assets/javascript/highlights.scm",
    new URL("./assets/javascript/highlights.scm", import.meta.url),
  )
  const javascript_language = resolveAssetPath(
    "@opentui/core/assets/javascript/tree-sitter-javascript.wasm",
    new URL("./assets/javascript/tree-sitter-javascript.wasm", import.meta.url),
  )
  const typescript_highlights = resolveAssetPath(
    "@opentui/core/assets/typescript/highlights.scm",
    new URL("./assets/typescript/highlights.scm", import.meta.url),
  )
  const typescript_language = resolveAssetPath(
    "@opentui/core/assets/typescript/tree-sitter-typescript.wasm",
    new URL("./assets/typescript/tree-sitter-typescript.wasm", import.meta.url),
  )
  const markdown_highlights = resolveAssetPath(
    "@opentui/core/assets/markdown/highlights.scm",
    new URL("./assets/markdown/highlights.scm", import.meta.url),
  )
  const markdown_language = resolveAssetPath(
    "@opentui/core/assets/markdown/tree-sitter-markdown.wasm",
    new URL("./assets/markdown/tree-sitter-markdown.wasm", import.meta.url),
  )
  const markdown_injections = resolveAssetPath(
    "@opentui/core/assets/markdown/injections.scm",
    new URL("./assets/markdown/injections.scm", import.meta.url),
  )
  const markdown_inline_highlights = resolveAssetPath(
    "@opentui/core/assets/markdown_inline/highlights.scm",
    new URL("./assets/markdown_inline/highlights.scm", import.meta.url),
  )
  const markdown_inline_language = resolveAssetPath(
    "@opentui/core/assets/markdown_inline/tree-sitter-markdown_inline.wasm",
    new URL("./assets/markdown_inline/tree-sitter-markdown_inline.wasm", import.meta.url),
  )
  const zig_highlights = resolveAssetPath(
    "@opentui/core/assets/zig/highlights.scm",
    new URL("./assets/zig/highlights.scm", import.meta.url),
  )
  const zig_language = resolveAssetPath(
    "@opentui/core/assets/zig/tree-sitter-zig.wasm",
    new URL("./assets/zig/tree-sitter-zig.wasm", import.meta.url),
  )

  return [
    {
      filetype: "javascript",
      aliases: ["javascriptreact"],
      queries: { highlights: [javascript_highlights] },
      wasm: javascript_language,
    },
    {
      filetype: "typescript",
      aliases: ["typescriptreact"],
      queries: { highlights: [typescript_highlights] },
      wasm: typescript_language,
    },
    {
      filetype: "markdown",
      queries: { highlights: [markdown_highlights], injections: [markdown_injections] },
      wasm: markdown_language,
      injectionMapping: {
        nodeTypes: { inline: "markdown_inline", pipe_table_cell: "markdown_inline" },
        infoStringMap: {
          javascript: "javascript",
          js: "javascript",
          jsx: "javascriptreact",
          javascriptreact: "javascriptreact",
          typescript: "typescript",
          ts: "typescript",
          tsx: "typescriptreact",
          typescriptreact: "typescriptreact",
          markdown: "markdown",
          md: "markdown",
        },
      },
    },
    {
      filetype: "markdown_inline",
      queries: { highlights: [markdown_inline_highlights] },
      wasm: markdown_inline_language,
    },
    {
      filetype: "zig",
      queries: { highlights: [zig_highlights] },
      wasm: zig_language,
    },
  ]
}
