// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file

export const defaultParserAssetPaths = [
  "assets/javascript/highlights.scm",
  "assets/javascript/tree-sitter-javascript.wasm",
  "assets/typescript/highlights.scm",
  "assets/typescript/tree-sitter-typescript.wasm",
  "assets/markdown/highlights.scm",
  "assets/markdown/tree-sitter-markdown.wasm",
  "assets/markdown/injections.scm",
  "assets/markdown_inline/highlights.scm",
  "assets/markdown_inline/tree-sitter-markdown_inline.wasm",
  "assets/zig/highlights.scm",
  "assets/zig/tree-sitter-zig.wasm",
] as const
