// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2026-03-20T21:07:24.696Z

import { fileURLToPath } from "node:url"
import type { FiletypeParserOptions } from "./types.js"

const javascript_highlights = fileURLToPath(new URL("./assets/javascript/highlights.scm", import.meta.url))
const javascript_language = fileURLToPath(new URL("./assets/javascript/tree-sitter-javascript.wasm", import.meta.url))
const typescript_highlights = fileURLToPath(new URL("./assets/typescript/highlights.scm", import.meta.url))
const typescript_language = fileURLToPath(new URL("./assets/typescript/tree-sitter-typescript.wasm", import.meta.url))
const markdown_highlights = fileURLToPath(new URL("./assets/markdown/highlights.scm", import.meta.url))
const markdown_language = fileURLToPath(new URL("./assets/markdown/tree-sitter-markdown.wasm", import.meta.url))
const markdown_injections = fileURLToPath(new URL("./assets/markdown/injections.scm", import.meta.url))
const markdown_inline_highlights = fileURLToPath(new URL("./assets/markdown_inline/highlights.scm", import.meta.url))
const markdown_inline_language = fileURLToPath(new URL("./assets/markdown_inline/tree-sitter-markdown_inline.wasm", import.meta.url))
const zig_highlights = fileURLToPath(new URL("./assets/zig/highlights.scm", import.meta.url))
const zig_language = fileURLToPath(new URL("./assets/zig/tree-sitter-zig.wasm", import.meta.url))

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        aliases: ["javascriptreact"],
        queries: {
          highlights: [javascript_highlights],
        },
        wasm: javascript_language,
      },
      {
        filetype: "typescript",
        aliases: ["typescriptreact"],
        queries: {
          highlights: [typescript_highlights],
        },
        wasm: typescript_language,
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [markdown_highlights],
          injections: [markdown_injections],
        },
        wasm: markdown_language,
        injectionMapping: {
          "nodeTypes": {
                    "inline": "markdown_inline",
                    "pipe_table_cell": "markdown_inline"
          },
          "infoStringMap": {
                    "javascript": "javascript",
                    "js": "javascript",
                    "jsx": "javascriptreact",
                    "javascriptreact": "javascriptreact",
                    "typescript": "typescript",
                    "ts": "typescript",
                    "tsx": "typescriptreact",
                    "typescriptreact": "typescriptreact",
                    "markdown": "markdown",
                    "md": "markdown"
          }
},
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [markdown_inline_highlights],
        },
        wasm: markdown_inline_language,
      },
      {
        filetype: "zig",
        queries: {
          highlights: [zig_highlights],
        },
        wasm: zig_language,
      },
    ]
  }
  return _cachedParsers
}
