name: Build Solid

on:
  push:

jobs:
  build:
    name: Solid - Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install dependencies
        run: bun install

      - name: Build core
        run: |
          cd packages/core
          bun run build

      - name: Build
        run: |
          cd packages/solid
          bun run build --ci

      - name: Run tests
        run: |
          cd packages/solid
          bun run test
